### ISSUE TITLE
Icon is nearly invisible in OSX Dark Mode

### ISSUE THREAD

**Issue by Elethiomel** [mariociabarra/wifriedx#3]
WifriedX doesn't appear to detect OSX dark mode and adjust the icon accordingly (using WiFriedX1.1 supplied binary)

**Comment by dvkch** [comment]
To me this has been fixed with commit a5e7bb9f683d4187e5dcaee13edd0a0ef3a0812a. The 1.2 dmg that you can download on the article page includes it.

**Comment by mariociabarra** [comment]
Yes - thanks forgot to close.
